---
title: "Topics"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 5
## Materials
-   [Access lecture slides](lectures/week4.pdf) 
-   [Access discussion template Rmd](discussion/week5_skeleton.Rmd)


# Week 4: Raster operations
## Materials
-   [Access lecture slides](lectures/week4.pdf) 
-   [Access lab template Rmd](labs/week4-template.Rmd)
-   [Access completed lab Rmd](labs/week4.Rmd)
-   [Check in quiz due by midnight 10-25-2023](https://forms.gle/WrVEYtckwERWCnfz8)
-   [Access discussion template Rmd](discussion/week4_skeleton.Rmd)
-   [Access completed discussion Rmd](discussion/week4_discussion.Rmd)
-   [Access completed discussion html](discussion/week4_discussion.html)

### Background reading
-   [Geocomputation with R, chapter 3](https://geocompr.robinlovelace.net/attr.html)
-   [Geocomputation with R, chapter 4](https://geocompr.robinlovelace.net/spatial-operations.html)
-   [Geocomputation with R, chapter 5](https://geocompr.robinlovelace.net/geometry-operations.html)

## Assignments
-   Assignment 2 posted on 10-17, due by midnight 10-28

# Week 3: Vector operations
## Materials
-   [Access lecture slides](lectures/week3.pdf) 
-   [Access lab template Rmd](labs/week3-template.Rmd)
-   [Access completed lab Rmd](labs/week3.Rmd)
-   [Access self-paced discussion module](discussion/week3.swc)
-   [Access completed discussion Rmd](discussion/week3_discussion.Rmd)

### Background reading
-   [GIS Fundamentals, chapter 9 part 1](readings/Bolstad-chapter9-part1.pdf)
-   [Geocomputation with R, chapter 4](https://geocompr.robinlovelace.net/spatial-operations.html)
-   [Geocomputation with R, chapter 5](https://geocompr.robinlovelace.net/geometry-operations.html) 

### Additional resources 
-   [**sf** overview](https://r-spatial.github.io/sf/index.html) 

## Assignments
-   Assignment 2 posted on 10-17, due by midnight 10-28

# Week 2: Intro to vector data
## Materials
-   [Access lecture slides](lectures/week2.pdf) 
-   [Access lab template Rmd](labs/week2-template.Rmd)
-   [Access completed lab Rmd](labs/week2.Rmd)
-   [Access completed lab html](labs/week2.html)

### Background reading
-   [GIS Fundamentals, chapter 2 part 2](readings/Bolstad-chapter2-part2.pdf)
-   [Geocomputation with R, chapter 2](https://geocompr.robinlovelace.net/spatial-class.html)
-   [Geocomputation with R, chapter 3](https://geocompr.robinlovelace.net/attr.html) 
-   [Geocomputation with R, chapter 7](https://r.geocompx.org/reproj-geo-data)

### Additional resources 
-   [**sf** overview](https://r-spatial.github.io/sf/index.html) 

## Assignments
-   Assignment 1 posted on 10-03, due by midnight 10-014

# Week 1: Intro to spatial data
## Materials
-   [Access lecture slides](lectures/week1.pdf)
-   [Access lab template Rmd](labs/week1-template.Rmd)
-   [Access completed lab Rmd](labs/week1.Rmd)
-   [Access completed lab html](labs/week1.html)
-   [Access discussion template Rmd](discussion/week1_skeleton.Rmd)
-   [Access completed discussion Rmd](discussion/week1_discussion.Rmd)
-   [Access completed discussion html](discussion/week1_discussion.html)

### Background reading
-   [Geocomputation with R, chapter 9](https://geocompr.robinlovelace.net/adv-map.html)
-   [GIS Fundamentals, chapter 2](readings/Bolstad-chapter2-part1.pdf)
-   [GIS Fundamentals, chapter 3](readings/Bolstad-chapter3.pdf)
-   [A Gentle Introduction to GIS, chapter 8](https://docs.qgis.org/3.16/en/docs/gentle_gis_introduction/coordinate_reference_systems.html)
-   [Esri, Geographic vs. projected coordinate systems](https://www.esri.com/arcgis-blog/products/arcgis-pro/mapping/gcs_vs_pcs/#:~:text=What%20is%20the%20difference%20between,map%20or%20a%20computer%20screen.)

### Additional resources
-   [John Snow: A Legacy of Disease Detectives (CDC)](https://blogs.cdc.gov/publichealthmatters/2017/03/a-legacy-of-disease-detectives/)
-   [How the north ended up on top of the map (Al Jazeera)](http://america.aljazeera.com/opinions/2014/2/maps-cartographycolonialismnortheurocentricglobe.html)
-   [Why maps point North on top? (Geospatial World)](https://www.geospatialworld.net/blogs/why-maps-point-north-on-top/)
-   [Why all world maps are wrong (Vox)](https://www.youtube.com/watch?v=kIID5FDi2JQ&t=3s)
-   [The true size of...](https://www.thetruesize.com/#?borders=1~!MTc4MDE0MDY.MzM4MTc4*MzYwMDAwMDA(MA~!CONTIGUOUS_US*MTAwMjQwNzU.MjUwMjM1MTc(MTc1)MA~!IN*NTI2NDA1MQ.Nzg2MzQyMQ)Mg~!CN*OTkyMTY5Nw.NzMxNDcwNQ(MjI1)MQ)
-   [Compare map projections (Metrocosm)](http://metrocosm.com/compare-map-projections.html)
-   [Guide to map projections (Axis Maps)](https://www.axismaps.com/guide/map-projections)
-   [**tmap** overview](https://r-tmap.github.io/tmap-book/)
-   [Guide to common errors in map production (Journal of maps)](https://files.taylorandfrancis.com/TJOM-suppmaterial-quick-guide.pdf)

## Assignments
-   Assignment 1 posted on 10-03, due by midnight 10-14

<!-- # Week 10: Active remote sensing -->
<!-- ## Lecture -->
<!-- ### Class materials -->
<!-- -   [Access lecture slides](lectures/week10.pdf) -->

<!-- ### Lab -->
<!-- -   [Optional LiDAR lab from EarthLab](https://www.earthdatascience.org/courses/use-data-open-source-python/data-stories/what-is-lidar-data/explore-lidar-point-clouds-plasio/) -->

<!-- ### Background reading -->
<!-- -   [Remote Sensing of the Environment, chapter 9](readings/Jensen-chapter9.pdf)\ -->
<!-- -   [Introduction to Lidar Remote Sensing Data (EarthLab)](https://www.earthdatascience.org/courses/use-data-open-source-python/data-stories/what-is-lidar-data/)\ -->
<!-- -  [Introduction to Interpreting Digital RADAR Images (MicroImages Inc.)](readings/MicroImages-RADAR-tutorial.pdf)  -->


<!-- ## Assignments -->
<!-- -   Assignment 4 posted on 11-16, due by midnight 12-03 -->



<!-- # Week 9: Image classification -->
<!-- ## Lecture -->
<!-- ### Class materials -->
<!-- -   [Access lecture slides](lectures/week9.pdf) -->

<!-- ## Lab -->
<!-- ### Class materials -->
<!-- -   [Download data](https://drive.google.com/drive/folders/1ON8FbDqcTjg2PKHmNGgyN7odTqpOnXla?usp=sharing) -->
<!-- -   [Access lab Rmd](labs/week9.Rmd)\ -->
<!-- -   [Access lab html](labs/week9.html) -->

<!-- ## Assignments -->
<!-- -   Assignment 4 posted on 11-16, due by midnight 12-03 -->

<!-- # Week 8: Remote sensing of vegetation -->
<!-- ## Lecture -->
<!-- ### Class materials -->
<!-- -   [Access lecture slides](lectures/week8.pdf) -->

<!-- ## Lab -->
<!-- ### Class materials -->
<!-- -   [Download data](https://drive.google.com/file/d/1e9ZwWoC6kmqy5r7WtDOkabYa02jMx_sd/view?usp=sharing) -->
<!-- -   [Access lab outline Rmd](labs/week8-outline.Rmd) -->
<!-- -   [Access lab Rmd](labs/week8.Rmd) -->
<!-- -   [Access lab html](labs/week8.html)\ -->


<!-- ### Background reading -->
<!-- -   [Remote Sensing of the Environment, chapter 10](readings/Jensen-chapter10.pdf) -->

<!-- **Note:** expert panel on hyperspectral remote sensing on Monday -->

<!-- ## Assignments -->
<!-- -   Assignment 4 posted on 11-16, due by midnight 12-03 -->

<!-- # Week 7: RS data collection -->
<!-- ## Lecture -->
<!-- ### Monday -->
<!-- -   [Access lecture slides](lectures/week7.pdf) -->
<!-- -   [Access lab Rmd](labs/week5.Rmd) -->
<!-- -   [Access lab html](labs/week5.html)\ -->
<!-- -   [CHECK IN](https://forms.gle/ugih7kuJrhSTaQgQ7) -->

<!-- ### Wednesday -->
<!-- -   [Access lecture slides](lectures/week7-pt2.pdf) -->
<!-- -   [EOSDIS Worldview](https://worldview.earthdata.nasa.gov/?l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,MODIS_Terra_SurfaceReflectance_Bands121,MODIS_Terra_CorrectedReflectance_Bands721,MODIS_Terra_CorrectedReflectance_Bands367&lg=true&l1=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,MODIS_Terra_CorrectedReflectance_TrueColor&lg1=true&ca=true&cv=39&t=2022-11-01-T22%3A42%3A21Z&t1=2022-11-01-T22%3A42%3A21Z) -->
<!-- -   [MODIS specifications](https://modis.gsfc.nasa.gov/about/specifications.php) -->
<!-- -   [CHECK IN](https://forms.gle/A928QG79MmUQtdzJ6) -->

<!-- ### Background reading -->
<!-- -   [Why is that forest red and cloud blue? (NASA Earth Observatory)](https://earthobservatory.nasa.gov/features/FalseColor) -->
<!-- -   [Remote Sensing of the Environment, chapter 1](readings/Jensen-chapter1.pdf) -->
<!-- -   [Remote Sensing of the Environment, chapter 2](readings/Jensen-chapter2.pdf) -->

<!-- ## Assignments -->
<!-- -   Assignment 3 posted on 10-26, due by midnight 11-12 -->


<!-- # Week 6: Intro to remote sensing -->
<!-- ## Lecture -->
<!-- ### Class materials -->
<!-- -   [Access lecture slides](lectures/week6.pdf) -->

<!-- ## Lab -->
<!-- -   No class on Wednesday 11/2 -->

<!-- ## Assignments -->
<!-- -   Assignment 3 posted on 10-26, due by midnight 11-12 -->

<!-- # Week 5: Raster operations -->
<!-- ## Lecture -->
<!-- ### Class materials -->
<!-- -   [Access lecture slides](lectures/week5.pdf) -->

<!-- ## Lab -->
<!-- ### Class materials  -->
<!-- -   [Access lab Rmd](labs/week5.Rmd) -->
<!-- -   [Access lab html](labs/week5.html) -->

<!-- ### Background reading -->
<!-- -   [Geocomputation with R, chapter 3](https://geocompr.robinlovelace.net/attr.html)   -->
<!-- -   [Geocomputation with R, chapter 4](https://geocompr.robinlovelace.net/spatial-operations.html) -->
<!-- -   [Geocomputation with R, chapter 5](https://geocompr.robinlovelace.net/geometry-operations.html) -->

<!-- ## Assignments -->
<!-- -   Assignment 3 posted on 10-26, due by midnight 11-12 -->


<!-- # Week 4: Expert panel + vector operations (cont'd) -->
<!-- ## Lecture -->
<!-- ### Class materials -->
<!-- -   [Access spatial data science expert panel slides](lectures/week4.pdf) -->

<!-- ## Lab -->
<!-- ### Class materials (continued from week 3) -->
<!-- -   [Access lab Rmd](labs/week3.Rmd) -->
<!-- -   [Access lab html](labs/week3.html) -->

<!-- ### Background reading (continued from week 3) -->
<!-- -   [Geocomputation with R, chapter 4](https://geocompr.robinlovelace.net/spatial-operations.html) -->
<!-- -   [Geocomputation with R, chapter 5](https://geocompr.robinlovelace.net/geometry-operations.html) -->

<!-- ### Additional resources -->
<!-- -   [**sf** overview](https://r-spatial.github.io/sf/index.html) -->

<!-- ## Assignments -->
<!-- -   Assignment 2 posted on 10-12, due by midnight 10-22 -->

<!-- # Week 3: Vector operations -->
<!-- ## Lecture -->
<!-- ### Class materials -->
<!-- -   [Access lecture slides](lectures/week3.pdf) -->

<!-- ### Background reading -->
<!-- -   [GIS Fundamentals, chapter 9 part 1](readings/Bolstad-chapter9-part1.pdf) -->

<!-- ### Additional resources -->
<!-- -   [Douglas-Peucker Algorithm (Cartography Playground)](https://cartography-playground.gitlab.io/playgrounds/douglas-peucker-algorithm/)   -->
<!-- -   [Visvalingam's Algorithm (Mike Bostok)](https://bost.ocks.org/mike/simplify/ -->
<!-- ) -->

<!-- ## Lab -->
<!-- ### Class materials -->
<!-- -   [CHECK IN](https://forms.gle/zrj8V6HyL9ro4Xmn7) -->
<!-- -   [Access lab Rmd](labs/week3.Rmd) -->
<!-- -   [Access lab html](labs/week3.html) -->

<!-- ### Background reading -->
<!-- -   [Geocomputation with R, chapter 4](https://geocompr.robinlovelace.net/spatial-operations.html) -->
<!-- -   [Geocomputation with R, chapter 5](https://geocompr.robinlovelace.net/geometry-operations.html) -->

<!-- ### Additional resources -->
<!-- -   [**sf** overview](https://r-spatial.github.io/sf/index.html) -->

<!-- ## Assignments -->
<!-- -   Assignment 2 posted on 10-12, due by midnight 10-22 -->






